name: Deploy to Windows Server

on:
  push:
    branches: 
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Action-SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }} 
          port: ${{ secrets.PORT }} 
          username: ${{ secrets.USERNAME }} 
          password: ${{ secrets.PASSWORD }}
          script: "C:\\deploy.bat"
            # whoami &  echo Pull or Clone... & ( if not exist C:\repos\ActionTestEx1\.git (git clone git@github.com:rhodi2436/ActionTestEx1.git C:\repos\ActionTestEx1   ) else (  cd /d C:\repos\ActionTestEx1  & git pull origin master )) & dotnet publish C:\repos\ActionTestEx1 -c Release --property:OutputPath=C:\publish_web\ActionTestEx1 & iisreset
